spring:
  application:
    name: auth-spring-security-v1
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

security:
  jwt:
    user:
      generator:
        AUTHJWT-BACKEND-BAKANO
    key:
      private: b8785b8c159eefc583e10ed8d3db0e02d75e534b014530ae621a94ac2c02b8ed

